inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Dangerfile
    - Gemfile
    - Guardfile
    - Rakefile
    - '*.gemspec'
    - '**/*.rb'
  TargetRubyVersion: 2.6

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*_test.rb

Style/Documentation:
  Enabled: false

Metrics:
  Exclude:
    - test/**/*_test.rb

Metrics/LineLength:
  Max: 100
