---
name: ci

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - ".rubocop.yml"
      - trace_method.gemspec
      - lib/**/*.rb
      - test/**
      - Rakefile
      - Gemfile
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - 2.6
          - 2.5
          - jruby
        include:
          - ruby: 2.6
            coverage: true
    env:
      COVERAGE: ${{ matrix.coverage }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run all tests
        run: bundle exec rake test
