---
name: ci

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - ".rubocop.yml"
      - trace_method.gemspec
      - lib/**/*.rb
      - test/**
      - Rakefile
      - Gemfile
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - 2.6
          - 2.5
          - jruby
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run all tests
        run: bundle exec rake test
  coverage:
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install --jobs 4 --retry 3
      - name: Install Code Climate
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
      - name: Calculate and report coverage
        env:
          COVERAGE: true
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ./cc-test-reporter before-build
          bundle exec rake test
          ls -al coverage/
          ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
